### PR TITLE
fix: bug with wrong files in context

### LINKED ISSUE #177: Reference error when in workspace with multiple scg-context.
In workspaces with multiple scg-contexts referencing the same files with the same folder structure, references between the files in different scg-contexts might be created. This is due to how the files are discovered by the client from disk.

### PR DESCRIPTION
**Pull request by vetlek**
Closes #177

### CODE REVIEW

File: client/src/util.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+import * as path from "path";
+
+export function getSearchPattern(worskspacePath: string, templatePath: string) {
```
Comment (einarsi) [inline client/src/util.ts:3]: Typo
